In [17]:
import pandas as pd 
# import matplotlib as plt

df = pd.read_csv("paniers.csv")
df.head(2)

,id_panier,label_panier,type_panier,id_utilisateur,actif,nombre_produits,date_publication,utilisateur_creation,date_creation,utilisateur_modification,date_modification,image,presentation,links
0,d19b22f0-9cb9-4c08-91e0-9fcae93adee1,MAM,PERSO,9f44a944-1b37-4bdb-b8b6-c478d2bca598,True,5,2025-05-13,mdydy155@gmail.com,2025-05-13,NaN,NaN,NaN,NaN,{'self': {'href': 'https://prix.nc/api/v1/pani...
1,5035a78d-a851-43ee-b32e-5e56741decba,Entretien/hygienne,PERSO,fdcf4a8d-742b-4710-a704-7fb842e12385,True,10,2025-04-27,rdawano@gmail.com,2025-04-01,rdawano@gmail.com,2025-04-27,NaN,NaN,{'self': {'href': 'https://prix.nc/api/v1/pani...

In [58]:
df.isnull().sum()

id_panier                   0
label_panier                0
type_panier                 0
id_utilisateur              0
actif                       0
nombre_produits             0
date_publication            0
utilisateur_creation        0
date_creation               0
utilisateur_modification    0
date_modification           0
image                       0
presentation                0
links                       0
dtype: int64

In [34]:
data = df 
data[["image"]] = data[["image"]].fillna("vide")
data[["image"]]
data.head(1)

,id_panier,label_panier,type_panier,id_utilisateur,actif,nombre_produits,date_publication,utilisateur_creation,date_creation,utilisateur_modification,date_modification,image,presentation,links
0,d19b22f0-9cb9-4c08-91e0-9fcae93adee1,MAM,PERSO,9f44a944-1b37-4bdb-b8b6-c478d2bca598,True,5,2025-05-13,mdydy155@gmail.com,2025-05-13,NaN,NaN,vide,NaN,{'self': {'href': 'https://prix.nc/api/v1/pani...

In [36]:
data[["presentation"]] = data[["presentation"]].fillna("Acunne")
data[["presentation"]].head(2)

  presentation
0       Acunne
1       Acunne

In [48]:
data[["date_modification"]].to_timestamp
dt = data
db = data
dt[["date_modification"]] = dt[["date_modification"]].fillna(pd.to_datetime("1999-01-01"))
dt["date_modification"] = pd.to_datetime(dt['date_modification']).dt.date
dt[["date_modification"]]

    date_modification
0          1999-01-01
1          2025-04-27
2          1999-01-01
3          1999-01-01
4          1999-01-01
..                ...
275        2018-01-09
276        2018-01-09
277        2018-01-09
278        2018-01-09
279        2018-04-03

[280 rows x 1 columns]

In [57]:
db["utilisateur_modification"] = db["utilisateur_modification"].fillna("vide")
db["utilisateur_modification"]

0                   vide
1      rdawano@gmail.com
2                   vide
3                   vide
4                   vide
             ...
275       Mathilde MENIL
276       Mathilde MENIL
277       Mathilde MENIL
278       Mathilde MENIL
279       Mathilde MENIL
Name: utilisateur_modification, Length: 280, dtype: str

In [60]:
db.head(12)

,id_panier,label_panier,type_panier,id_utilisateur,actif,nombre_produits,date_publication,utilisateur_creation,date_creation,utilisateur_modification,date_modification,image,presentation,links
0,d19b22f0-9cb9-4c08-91e0-9fcae93adee1,MAM,PERSO,9f44a944-1b37-4bdb-b8b6-c478d2bca598,True,5,2025-05-13,mdydy155@gmail.com,2025-05-13,vide,1999-01-01,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
1,5035a78d-a851-43ee-b32e-5e56741decba,Entretien/hygienne,PERSO,fdcf4a8d-742b-4710-a704-7fb842e12385,True,10,2025-04-27,rdawano@gmail.com,2025-04-01,rdawano@gmail.com,2025-04-27,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
2,75a4b165-cb59-4e9c-8331-a5c7319d4c36,sucres,PERSO,564618f1-7e4a-4a77-8398-463c3bfee833,True,0,2025-04-24,cuewapurumarielouise@gmail.com,2025-04-24,vide,1999-01-01,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
3,37520072-d798-4552-9d7a-b45fb28fdfec,courses classiques,PERSO,accfb24e-ab3c-40d0-a3fd-eca58a55de0b,True,0,2025-04-11,i.regis.martin@gmail.com,2025-04-11,vide,1999-01-01,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
4,e1e04e24-1c65-4b22-87e8-250daf9b39f0,TEST,PERSO,6d850679-98bc-4c76-9576-ac92acb2bbe9,True,6,2025-04-01,fred.decourt@gmail.com,2025-04-01,vide,1999-01-01,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
5,55688f7c-528f-41d2-9654-6f2ca9e28a77,pmm,PERSO,57a1b952-fd92-4318-a3d9-c918f1f2bae8,True,0,2025-03-31,pierre.magnier63@gmail.com,2025-03-31,vide,1999-01-01,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
6,67c4ab98-2e5d-4830-a4ec-f341313287a0,panier 1,PERSO,d2ad396b-1edf-410d-8714-1157a60d85df,True,1,2025-03-31,Iouri MROZ,2025-03-30,Iouri MROZ,2025-03-31,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
7,97511ef8-3f73-45dc-8fdd-e9a093b545f0,Achat,PERSO,7bb81d30-02ea-4dbb-9649-d00c42849fd3,True,0,2025-03-23,sheyen.finau@gmail.com,2025-03-23,vide,1999-01-01,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
8,357ef0f1-7c25-4853-b8fe-567e60020996,Mensuel,PERSO,73fcc864-0335-4e26-8266-a7a1700f29d8,True,33,2025-03-22,prowilson56@gmail.com,2025-03-21,prowilson56@gmail.com,2025-03-22,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
9,6b77c82d-b775-46b1-bec6-40678bf63151,Quotidienne,PERSO,73fcc864-0335-4e26-8266-a7a1700f29d8,True,0,2025-03-21,prowilson56@gmail.com,2025-03-21,vide,1999-01-01,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
10,1677eaac-7a28-4daa-b0f3-fd7c771c8750,Epicerie,PERSO,9189c310-eeb0-4432-b964-a30de98c4025,True,3,2025-03-12,Claude,2025-03-12,Claude,2025-03-12,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...
11,512b130b-c414-490d-86ae-bafa50a541a4,Courses,PERSO,a3a0fecf-8f9f-4100-8a91-30e235eb32e2,True,41,2025-02-28,Lensnepa,2025-02-28,vide,1999-01-01,vide,Acunne,{'self': {'href': 'https://prix.nc/api/v1/pani...